export default {
  // -----// LOGIN //-----//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // -----// SET_MODAL //-----//
  SET_MODAL_START: 'SET_MODAL_START',
  SET_MODAL_SUCCESS: 'SET_MODAL_SUCCESS',
  SET_MODAL_FAILURE: 'SET_MODAL_FAILURE',

  // -----// GET_ALL_FEES //-----//
  GET_ALL_FEES_START: 'GET_ALL_FEES_START',
  GET_ALL_FEES_SUCCESS: 'GET_ALL_FEES_SUCCESS',
  GET_ALL_FEES_FAILURE: 'GET_ALL_FEES_FAILURE',

  // -----// GET_ASSET_FEES //-----//
  GET_ASSET_FEES_START: 'GET_ASSET_FEES_START',
  GET_ASSET_FEES_SUCCESS: 'GET_ASSET_FEES_SUCCESS',
  GET_ASSET_FEES_FAILURE: 'GET_ASSET_FEES_FAILURE',

  // -----// LOGOUT //-----//
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  // ----- // RESET_PASSWORD // ----- //
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  // ----- // CHANGE_PASSWORD // ----- //
  CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  // ----- // SIGNUP // ----- //
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  // ----- // SET_CURRENT_PAIR // ----- //
  SET_CURRENT_PAIR_START: 'SET_CURRENT_PAIR_START',
  SET_CURRENT_PAIR_SUCCESS: 'SET_CURRENT_PAIR_SUCCESS',
  SET_CURRENT_PAIR_FAILURE: 'SET_CURRENT_PAIR_FAILURE',

  // ----- // SET_CURRENT_CONTRACT // ----- //
  SET_CURRENT_CONTRACT_START: 'SET_CURRENT_CONTRACT_START',
  SET_CURRENT_CONTRACT_SUCCESS: 'SET_CURRENT_CONTRACT_SUCCESS',
  SET_CURRENT_CONTRACT_FAILURE: 'SET_CURRENT_CONTRACT_FAILURE',

  // ----- // SET_LANGUAGE // ----- //
  SET_LANGUAGE_START: 'SET_LANGUAGE_START',
  SET_LANGUAGE_SUCCESS: 'SET_LANGUAGE_SUCCESS',
  SET_LANGUAGE_FAILURE: 'SET_LANGUAGE_FAILURE',

  // ----- // SOCKET // ----- //
  SOCKET_OPEN: 'SOCKET_OPEN',
  SOCKET_CLOSE: 'SOCKET_CLOSE',
  SOCKET_CONNECTED: 'SOCKET_CONNECTED',
  SOCKET_SEND_CHANNEL: 'SOCKET_SEND_CHANNEL',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',

  // ----- // GET_ASSETS // ----- //
  GET_ASSETS_START: 'GET_ASSETS_START',
  GET_ASSETS_SUCCESS: 'GET_ASSETS_SUCCESS',
  GET_ASSETS_FAILURE: 'GET_ASSETS_FAILURE',

  // ----- // GET_ASSET_PAIRS // ----- //
  GET_ASSET_PAIRS_START: 'GET_ASSET_PAIRS_START',
  GET_ASSET_PAIRS_SUCCESS: 'GET_ASSET_PAIRS_SUCCESS',
  GET_ASSET_PAIRS_FAILURE: 'GET_ASSET_PAIRS_FAILURE',

  // ----- // UPDATE_ASSET_PAIRS // ----- //
  UPDATE_ASSET_PAIRS: 'UPDATE_ASSET_PAIRS',

  // ----- // UPDATE_TOP_ASSETS_PAIRS // ----- //
  UPDATE_TOP_ASSETS_PAIRS: 'UPDATE_TOP_ASSETS_PAIRS',

  // ----- // GET_FAVORITE_ASSET_PAIRS // ----- //
  GET_FAVORITE_ASSET_PAIRS_START: 'GET_FAVORITE_ASSET_PAIRS_START',
  GET_FAVORITE_ASSET_PAIRS_SUCCESS: 'GET_FAVORITE_ASSET_PAIRS_SUCCESS',
  GET_FAVORITE_ASSET_PAIRS_FAILURE: 'GET_FAVORITE_ASSET_PAIRS_FAILURE',

  // ----- // GET_SPOT_ASSET_PAIRS // ----- //
  GET_SPOT_ASSET_PAIRS_START: 'GET_SPOT_ASSET_PAIRS_START',
  GET_SPOT_ASSET_PAIRS_SUCCESS: 'GET_SPOT_ASSET_PAIRS_SUCCESS',
  GET_SPOT_ASSET_PAIRS_FAILURE: 'GET_SPOT_ASSET_PAIRS_FAILURE',

  // ----- // GET_SPOT_ASSET_PAIRS // ----- //
  GET_MARGIN_ASSET_PAIRS_START: 'GET_MARGIN_ASSET_PAIRS_START',
  GET_MARGIN_ASSET_PAIRS_SUCCESS: 'GET_MARGIN_ASSET_PAIRS_SUCCESS',
  GET_MARGIN_ASSET_PAIRS_FAILURE: 'GET_MARGIN_ASSET_PAIRS_FAILURE',

  // ----- // UPDATE_FAVORITE_ASSET_PAIRS // ----- //
  UPDATE_FAVORITE_ASSET_PAIR_START: 'UPDATE_FAVORITE_ASSET_PAIR_START',
  UPDATE_FAVORITE_ASSET_PAIR_SUCCESS: 'UPDATE_FAVORITE_ASSET_PAIR_SUCCESS',
  UPDATE_FAVORITE_ASSET_PAIR_FAILURE: 'UPDATE_FAVORITE_ASSET_PAIR_FAILURE',

  // ----- // GET_TOPICS // ----- //
  GET_TOPICS_START: 'GET_TOPICS_START',
  GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
  GET_TOPICS_FAILURE: 'GET_TOPICS_FAILURE',

  // ----- // SEND_CONTACTUS_FORM // ----- //
  SEND_CONTACTUS_FORM_START: 'SEND_CONTACTUS_FORM_START',
  SEND_CONTACTUS_FORM_SUCCESS: 'SEND_CONTACTUS_FORM_SUCCESS',
  SEND_CONTACTUS_FORM_FAILURE: 'SEND_CONTACTUS_FORM_FAILURE',

  // ----- // CONFIRM_EMAIL // ----- //
  CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
  CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
  CONFIRM_EMAIL_FAILURE: 'CONFIRM_EMAIL_FAILURE',

  // ----- // EXCHANGE_RATE // ----- //
  EXCHANGE_RATE_START: 'EXCHANGE_RATE_START',
  EXCHANGE_RATE_SUCCESS: 'EXCHANGE_RATE_SUCCESS',
  EXCHANGE_RATE_FAILURE: 'EXCHANGE_RATE_FAILURE',

  // ----- // EXCHANGE // ----- //
  EXCHANGE_START: 'EXCHANGE_START',
  EXCHANGE_SUCCESS: 'EXCHANGE_SUCCESS',
  EXCHANGE_FAILURE: 'EXCHANGE_FAILURE',

  // ----- // GET_EXCHANGE_HISTORY // ----- //
  GET_EXCHANGE_HISTORY_START: 'GET_EXCHANGE_HISTORY_START',
  GET_EXCHANGE_HISTORY_SUCCESS: 'GET_EXCHANGE_HISTORY_SUCCESS',
  GET_EXCHANGE_HISTORY_FAILURE: 'GET_EXCHANGE_HISTORY_FAILURE',

  // ----- // GET_TOP_PAIRS // ----- //
  GET_TOP_PAIRS_START: 'GET_TOP_PAIRS_START',
  GET_TOP_PAIRS_SUCCESS: 'GET_TOP_PAIRS_SUCCESS',
  GET_TOP_PAIRS_FAILURE: 'GET_TOP_PAIRS_FAILURE',

  /**
   * USERS
   */

  /**
   * TOKENS
   */

  // ----- // GET_TOKENS // ----- //
  GET_TOKENS_START: 'GET_TOKENS_START',
  GET_TOKENS_SUCCESS: 'GET_TOKENS_SUCCESS',
  GET_TOKENS_FAILURE: 'GET_TOKENS_FAILURE',

  // ----- // CREATE_TOKENS // ----- //
  CREATE_TOKENS_START: 'CREATE_TOKENS_START',
  CREATE_TOKENS_SUCCESS: 'CREATE_TOKENS_SUCCESS',
  CREATE_TOKENS_FAILURE: 'CREATE_TOKENS_FAILURE',

  // ----- // DISABLE_TOKENS // ----- //
  DISABLE_TOKENS_START: 'DISABLE_TOKENS_START',
  DISABLE_TOKENS_SUCCESS: 'DISABLE_TOKENS_SUCCESS',
  DISABLE_TOKENS_FAILURE: 'DISABLE_TOKENS_FAILURE',

  // ----- // DELETE_TOKENS // ----- //
  DELETE_TOKENS_START: 'DELETE_TOKENS_START',
  DELETE_TOKENS_SUCCESS: 'DELETE_TOKENS_SUCCESS',
  DELETE_TOKENS_FAILURE: 'DELETE_TOKENS_FAILURE',

  // ----- // RESET_PASSWORD // ----- //
  USERS_RESET_PASSWORD_START: 'USERS_RESET_PASSWORD_START',
  USERS_RESET_PASSWORD_SUCCESS: 'USERS_RESET_PASSWORD_SUCCESS',
  USERS_RESET_PASSWORD_FAILURE: 'USERS_RESET_PASSWORD_FAILURE',

  // ----- // GET_USER_DATA // ----- //
  GET_USER_DATA_START: 'GET_USER_DATA_START',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',

  // ----- // GET_USER_SECURITY_DATA // ----- //
  GET_USER_SECURITY_DATA_START: 'GET_USER_SECURITY_DATA_START',
  GET_USER_SECURITY_DATA_SUCCESS: 'GET_USER_SECURITY_DATA_SUCCESS',
  GET_USER_SECURITY_DATA_FAILURE: 'GET_USER_SECURITY_DATA_FAILURE',

  // ----- // CHECK_USER_ANTIPHISHING_DATA // ----- //
  CHECK_USER_ANTIPHISHING_DATA_START: 'CHECK_USER_ANTIPHISHING_DATA_START',
  CHECK_USER_ANTIPHISHING_DATA_SUCCESS: 'CHECK_USER_ANTIPHISHING_DATA_SUCCESS',
  CHECK_USER_ANTIPHISHING_DATA_FAILURE: 'CHECK_USER_ANTIPHISHING_DATA_FAILURE',

  // ----- // SET_USER_ANTIPHISHING_DATA // ----- //
  SET_USER_ANTIPHISHING_DATA_START: 'SET_USER_ANTIPHISHING_DATA_START', // has been used
  SET_USER_ANTIPHISHING_DATA_SUCCESS: 'SET_USER_ANTIPHISHING_DATA_SUCCESS', // nas not been used, maybe will need in future.
  SET_USER_ANTIPHISHING_DATA_FAILURE: 'SET_USER_ANTIPHISHING_DATA_FAILURE', // nas not been used, maybe will need in future.

  // ----- // UPDATE_USER_DATA // ----- //
  UPDATE_USER_DATA_START: 'UPDATE_USER_DATA_START',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_FAILURE: 'UPDATE_USER_DATA_FAILURE',

  // ----- // UPDATE_DOCUMENTS // ----- //
  UPDATE_DOCUMENTS_START: 'UPDATE_DOCUMENTS_START',
  UPDATE_DOCUMENTS_SUCCESS: 'UPDATE_DOCUMENTS_SUCCESS',
  UPDATE_DOCUMENTS_FAILURE: 'UPDATE_DOCUMENTS_FAILURE',

  // ----- // DELETE_DOCUMENTS // ----- //
  DELETE_DOCUMENTS_START: 'DELETE_DOCUMENTS_START',
  DELETE_DOCUMENTS_SUCCESS: 'DELETE_DOCUMENTS_SUCCESS',
  DELETE_DOCUMENTS_FAILURE: 'DELETE_DOCUMENTS_FAILURE',

  // ----- // DASHBOARD // ----- //
  GET_DASHBOARD_START: 'GET_DASHBOARD_START',
  GET_DASHBOARD_SUCCESS: 'GET_DASHBOARD_SUCCESS',
  GET_DASHBOARD_FAILURE: 'GET_DASHBOARD_FAILURE',

  // ----- // GET_IDENTIFICATION // ----- //
  GET_IDENTIFICATION_START: 'GET_IDENTIFICATION_START',
  GET_IDENTIFICATION_SUCCESS: 'GET_IDENTIFICATION_SUCCESS',
  GET_IDENTIFICATION_FAILURE: 'GET_IDENTIFICATION_FAILURE',

  // ----- // GET SECRET KEY // ----- //
  GET_SECRET_KEY_START: 'GET_SECRET_KEY_START',
  GET_SECRET_KEY_SUCCESS: 'GET_SECRET_KEY_SUCCESS',
  GET_SECRET_KEY_FAILURE: 'GET_SECRET_KEY_FAILURE',

  // ----- // VERIFY_USER_IP // ----- //
  VERIFY_USER_IP_START: 'VERIFY_USER_IP_START',
  VERIFY_USER_IP_SUCCESS: 'VERIFY_USER_IP_SUCCESS',
  VERIFY_USER_IP_FAILURE: 'VERIFY_USER_IP_FAILURE',

  // ----- // RECENT_CODE // ----- //
  RECENT_CODE_START: 'RECENT_CODE_START',
  RECENT_CODE_SUCCESS: 'RECENT_CODE_SUCCESS',
  RECENT_CODE_FAILURE: 'RECENT_CODE_FAILURE',

  // ----- // UPDATE_TOKEN_DISKOUNT // ----- //
  UPDATE_TOKEN_DISKOUNT_START: 'UPDATE_TOKEN_DISKOUNT_START',
  UPDATE_TOKEN_DISKOUNT_SUCCESS: 'UPDATE_TOKEN_DISKOUNT_SUCCESS',
  UPDATE_TOKEN_DISKOUNT_FAILURE: 'UPDATE_TOKEN_DISKOUNT_FAILURE',

  // ----- // GET_TOKEN_DISKOUNT // ----- //
  GET_TOKEN_DISKOUNT_START: 'GET_TOKEN_DISKOUNT_START',
  GET_TOKEN_DISKOUNT_SUCCESS: 'GET_TOKEN_DISKOUNT_SUCCESS',
  GET_TOKEN_DISKOUNT_FAILURE: 'GET_TOKEN_DISKOUNT_FAILURE',

  /**
   * SPOT TRADE
   */
  // ----- // GET_ORDERS_LIST // ----- //
  SPOT_GET_ORDERS_LIST_START: 'SPOT_GET_ORDERS_LIST_START',
  SPOT_GET_ORDERS_LIST_SUCCESS: 'SPOT_GET_ORDERS_LIST_SUCCESS',
  SPOT_GET_ORDERS_LIST_FAILURE: 'SPOT_GET_ORDERS_LIST_FAILURE',
  UPDATE_SPOT_OPEN_ORDERS: 'UPDATE_SPOT_OPEN_ORDERS',

  // ----- // CANCEL_OPEN_ORDER // ----- //
  SPOT_CANCEL_OPEN_ORDER_START: 'SPOT_CANCEL_OPEN_ORDER_START',
  SPOT_CANCEL_OPEN_ORDER_SUCCESS: 'SPOT_CANCEL_OPEN_ORDER_SUCCESS',
  SPOT_CANCEL_OPEN_ORDER_FAILURE: 'SPOT_CANCEL_OPEN_ORDER_FAILURE',

  // ----- // CANCEL_ALL_ORDERS // ----- //
  SPOT_CANCEL_ALL_ORDERS_START: 'SPOT_CANCEL_ALL_ORDERS_START',
  SPOT_CANCEL_ALL_ORDERS_SUCCESS: 'SPOT_CANCEL_ALL_ORDES_SUCCESS',
  SPOT_CANCEL_ALL_ORDERS_FAILURE: 'SPOT_CANCEL_ALL_ORDERS_FAILURE',

  // ----- // CANCEL_ALL_ASSETS_ORDERS // ----- //
  SPOT_CANCEL_ALL_ASSETS_ORDERS_START: 'SPOT_CANCEL_ALL_ASSETS_ORDERS_START',
  SPOT_CANCEL_ALL_ASSETS_ORDERS_SUCCESS:
    'SPOT_CANCEL_ALL_ASSETS_ORDERS_SUCCESS',
  SPOT_CANCEL_ALL_ASSETS_ORDERS_FAILURE:
    'SPOT_CANCEL_ALL_ASSETS_ORDERS_FAILURE',

  // ----- // GET_ORDERS_HISTORY // ----- //
  SPOT_GET_ORDERS_HISTORY_START: 'SPOT_GET_ORDERS_HISTORY_START',
  SPOT_GET_ORDERS_HISTORY_SUCCESS: 'SPOT_GET_ORDERS_HISTORY_SUCCESS',
  SPOT_GET_ORDERS_HISTORY_FAILURE: 'SPOT_GET_ORDERS_HISTORY_FAILURE',
  UPDATE_SPOT_CLOSED_ORDERS: 'UPDATE_SPOT_CLOSED_ORDERS',

  // ----- // GET_TRADE_HISTORY // ----- //
  SPOT_GET_TRADE_HISTORY_START: 'SPOT_GET_TRADE_HISTORY_START',
  SPOT_GET_TRADE_HISTORY_SUCCESS: 'SPOT_GET_TRADE_HISTORY_SUCCESS',
  SPOT_GET_TRADE_HISTORY_FAILURE: 'SPOT_GET_TRADE_HISTORY_FAILURE',

  // ----- // GET_ORDER_BOOK // ----- //
  SPOT_GET_ORDER_BOOK_START: 'SPOT_GET_ORDER_BOOK_START',
  SPOT_GET_ORDER_BOOK_SUCCESS: 'SPOT_GET_ORDER_BOOK_SUCCESS',
  SPOT_GET_ORDER_BOOK_FAILURE: 'SPOT_GET_ORDER_BOOK_FAILURE',
  UPDATE_SPOT_ORDER_BOOK: 'UPDATE_SPOT_ORDER_BOOK',

  // ----- // GET_RECENT_TRADES // ----- //
  SPOT_GET_RECENT_TRADES_START: 'SPOT_GET_RECENT_TRADES_START',
  SPOT_GET_RECENT_TRADES_SUCCESS: 'SPOT_GET_RECENT_TRADES_SUCCESS',
  SPOT_GET_RECENT_TRADES_FAILURE: 'SPOT_GET_RECENT_TRADES_FAILURE',
  UPDATE_SPOT_RECENT_TRADES: 'UPDATE_SPOT_RECENT_TRADES',

  /**
   * MARGIN TRADE
   */
  // ----- // GET_ORDERS_LIST // ----- //
  MARGIN_GET_ORDERS_LIST_START: 'MARGIN_GET_ORDERS_LIST_START',
  MARGIN_GET_ORDERS_LIST_SUCCESS: 'MARGIN_GET_ORDERS_LIST_SUCCESS',
  MARGIN_GET_ORDERS_LIST_FAILURE: 'MARGIN_GET_ORDERS_LIST_FAILURE',
  UPDATE_MARGIN_OPEN_ORDERS: 'UPDATE_MARGIN_OPEN_ORDERS',

  // ----- // CANCEL_OPEN_ORDER // ----- //
  MARGIN_CANCEL_OPEN_ORDER_START: 'MARGIN_CANCEL_OPEN_ORDER_START',
  MARGIN_CANCEL_OPEN_ORDER_SUCCESS: 'MARGIN_CANCEL_OPEN_ORDER_SUCCESS',
  MARGIN_CANCEL_OPEN_ORDER_FAILURE: 'MARGIN_CANCEL_OPEN_ORDER_FAILURE',

  // ----- // CANCEL_ALL_ORDERS // ----- //
  MARGIN_CANCEL_ALL_ORDERS_START: 'MARGIN_CANCEL_ALL_ORDERS_START',
  MARGIN_CANCEL_ALL_ORDERS_SUCCESS: 'MARGIN_CANCEL_ALL_ORDES_SUCCESS',
  MARGIN_CANCEL_ALL_ORDERS_FAILURE: 'MARGIN_CANCEL_ALL_ORDERS_FAILURE',

  // ----- // GET_ORDERS_HISTORY // ----- //
  MARGIN_GET_ORDERS_HISTORY_START: 'MARGIN_GET_ORDERS_HISTORY_START',
  MARGIN_GET_ORDERS_HISTORY_SUCCESS: 'MARGIN_GET_ORDERS_HISTORY_SUCCESS',
  MARGIN_GET_ORDERS_HISTORY_FAILURE: 'MARGIN_GET_ORDERS_HISTORY_FAILURE',
  UPDATE_MARGIN_CLOSED_ORDERS: 'UPDATE_MARGIN_CLOSED_ORDERS',

  // ----- // GET_TRADE_HISTORY // ----- //
  MARGIN_GET_TRADE_HISTORY_START: 'MARGIN_GET_TRADE_HISTORY_START',
  MARGIN_GET_TRADE_HISTORY_SUCCESS: 'MARGIN_GET_TRADE_HISTORY_SUCCESS',
  MARGIN_GET_TRADE_HISTORY_FAILURE: 'MARGIN_GET_TRADE_HISTORY_FAILURE',

  // ----- // GET_LOW_RISK // ----- //
  MARGIN_GET_LOW_RISK_START: 'MARGIN_GET_LOW_RISK_START',
  MARGIN_GET_LOW_RISK_SUCCESS: 'MARGIN_GET_LOW_RISK_SUCCESS',
  MARGIN_GET_LOW_RISK_FAILURE: 'MARGIN_GET_LOW_RISK_FAILURE',

  // ----- // GET_BALANCE // ----- //
  MARGIN_GET_BALANCE_START: 'MARGIN_GET_BALANCE_START',
  MARGIN_GET_BALANCE_SUCCESS: 'MARGIN_GET_BALANCE_SUCCESS',
  MARGIN_GET_BALANCE_FAILURE: 'MARGIN_GET_BALANCE_FAILURE',

  // ----- // GET_BORROWS // ----- //
  MARGIN_GET_BORROWS_START: 'MARGIN_GET_BORROWS_START',
  MARGIN_GET_BORROWS_SUCCESS: 'MARGIN_GET_BORROWS_SUCCESS',
  MARGIN_GET_BORROWS_FAILURE: 'MARGIN_GET_BORROWS_FAILURE',

  // ----- // GET_SINGLE_BORROW // ----- //
  MARGIN_GET_SINGLE_BORROW_START: 'MARGIN_GET_SINGLE_BORROW_START',
  MARGIN_GET_SINGLE_BORROW_SUCCESS: 'MARGIN_GET_SINGLE_BORROW_SUCCESS',
  MARGIN_GET_SINGLE_BORROW_FAILURE: 'MARGIN_GET_SINGLE_BORROW_FAILURE',

  // ----- // GET_SINGLE_REPAY // ----- //
  MARGIN_GET_SINGLE_REPAY_START: 'MARGIN_GET_SINGLE_REPAY_START',
  MARGIN_GET_SINGLE_REPAY_SUCCESS: 'MARGIN_GET_SINGLE_REPAY_SUCCESS',
  MARGIN_GET_SINGLE_REPAY_FAILURE: 'MARGIN_GET_SINGLE_REPAY_FAILURE',

  // ----- // MARGIN_POST_REPAY // ----- //
  MARGIN_POST_REPAY_START: 'MARGIN_POST_REPAY_START',
  MARGIN_POST_REPAY_SUCCESS: 'MARGIN_POST_REPAY_SUCCESS',
  MARGIN_POST_REPAY_FAILURE: 'MARGIN_POST_REPAY_FAILURE',

  // ----- // MARGIN_POST_TRANSFORM // ----- //
  MARGIN_POST_TRANSFORM_START: 'MARGIN_POST_TRANSFORM_START',
  MARGIN_POST_TRANSFORM_SUCCESS: 'MARGIN_POST_TRANSFORM_SUCCESS',
  MARGIN_POST_TRANSFORM_FAILURE: 'MARGIN_POST_TRANSFORM_FAILURE',

  // ----- // MARGIN_POST_BORROW // ----- //
  MARGIN_POST_BORROW_START: 'MARGIN_POST_BORROW_START',
  MARGIN_POST_BORROW_SUCCESS: 'MARGIN_POST_BORROW_SUCCESS',
  MARGIN_POST_BORROW_FAILURE: 'MARGIN_POST_BORROW_FAILURE',

  // ----- // TEMPORARY_SELECTED_TRADE // ----- //
  TEMPORARY_SELECTED_TRADE: 'TEMPORARY_SELECTED_TRADE',

  // ----- // CLEAR_SELECTED_TRADE // ----- //
  CLEAR_SELECTED_TRADE: 'CLEAR_SELECTED_TRADE',

  // ----- // GET_WALLETS // ----- //
  GET_WALLETS_START: 'GET_WALLETS_START',
  GET_WALLETS_SUCCESS: 'GET_WALLETS_SUCCESS',
  GET_WALLETS_FAILURE: 'GET_WALLETS_FAILURE',
  UPDATE_WALLETS: 'UPDATE_WALLETS',

  // ----- // GET_WALLET // ----- //
  GET_WALLET_START: 'GET_WALLET_START',
  GET_WALLET_SUCCESS: 'GET_WALLET_SUCCESS',
  GET_WALLET_FAILURE: 'GET_WALLET_FAILURE',

  GET_ALL_COINS_START: 'GET_ALL_COINS_START',
  GET_ALL_COINS_SUCCESS: 'GET_ALL_COINS_SUCCESS',
  GET_ALL_COINS_FAILURE: 'GET_ALL_COINS_FAILURE',

  GET_DEPOSIT_ADDRESS_START: 'GET_DEPOSIT_ADDRESS_START',
  GET_DEPOSIT_ADDRESS_SUCCESS: 'GET_DEPOSIT_ADDRESS_SUCCESS',
  GET_DEPOSIT_ADDRESS_FAILURE: 'GET_DEPOSIT_ADDRESS_FAILURE',

  // ----- // GET_WALLETS_TRANSACTIONS // ----- //
  GET_WALLETS_TRANSACTIONS_START: 'GET_WALLETS_TRANSACTIONS_START',
  GET_WALLETS_TRANSACTIONS_SUCCESS: 'GET_WALLETS_TRANSACTIONS_SUCCESS',
  GET_WALLETS_TRANSACTIONS_FAILURE: 'GET_WALLETS_TRANSACTIONS_FAILURE',

  // ----- // GET_WALLETS_TRANSFER // ----- //
  GET_WALLETS_TRANSFER_START: 'GET_WALLETS_TRANSFER_START',
  GET_WALLETS_TRANSFER_SUCCESS: 'GET_WALLETS_TRANSFER_SUCCESS',
  GET_WALLETS_TRANSFER_FAILURE: 'GET_WALLETS_TRANSFER_FAILURE',

  // ----- // GET_WALLETS_DEPOSITS // ----- //
  GET_WALLETS_DEPOSITS_START: 'GET_WALLETS_DEPOSITS_START',
  GET_WALLETS_DEPOSITS_SUCCESS: 'GET_WALLETS_DEPOSITS_SUCCESS',
  GET_WALLETS_DEPOSITS_FAILURE: 'GET_WALLETS_DEPOSITS_FAILURE',

  // ----- // GET_WALLETS_WITHDRAWALS // ----- //
  GET_WALLETS_WITHDRAWALS_START: 'GET_WALLETS_WITHDRAWALS_START',
  GET_WALLETS_WITHDRAWALS_SUCCESS: 'GET_WALLETS_WITHDRAWALS_SUCCESS',
  GET_WALLETS_WITHDRAWALS_FAILURE: 'GET_WALLETS_WITHDRAWALS_FAILURE',

  // ----- // POST_GENERATE_ADRESS_WALLETS // ----- //
  POST_GENERATE_ADRESS_WALLETS_START: 'POST_GENERATE_ADRESS_WALLETS_START',
  POST_GENERATE_ADRESS_WALLETS_SUCCESS: 'POST_GENERATE_ADRESS_WALLETS_SUCCESS',
  POST_GENERATE_ADRESS_WALLETS_FAILURE: 'POST_GENERATE_ADRESS_WALLETS_FAILURE',

  // ----- // POST_CREATE_WITHDRAWAL_REQUEST // ----- //
  POST_CREATE_WITHDRAWAL_REQUEST_START: 'POST_CREATE_WITHDRAWAL_REQUEST_START',
  POST_CREATE_WITHDRAWAL_REQUEST_SUCCESS:
    'POST_CREATE_WITHDRAWAL_REQUEST_SUCCESS',
  POST_CREATE_WITHDRAWAL_REQUEST_FAILURE:
    'POST_CREATE_WITHDRAWAL_REQUEST_FAILURE',

  // ----- // POST_CREATE_WITHDRAWAL_GOLD_REQUEST // ----- //
  POST_CREATE_WITHDRAWAL_GOLD_REQUEST_START:
    'POST_CREATE_WITHDRAWAL_GOLD_REQUEST_START',
  POST_CREATE_WITHDRAWAL_GOLD_REQUEST_SUCCESS:
    'POST_CREATE_WITHDRAWAL_GOLD_REQUEST_SUCCESS',
  POST_CREATE_WITHDRAWAL_GOLD_REQUEST_FAILURE:
    'POST_CREATE_WITHDRAWAL_REQUEST_GOLD_FAILURE',

  // ----- // POST_CREATE_WITHDRAWAL_GOLD_REQUEST // ----- //
  GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_START:
    'GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_START',
  GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_SUCCESS:
    'GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_SUCCESS',
  GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_FAILURE:
    'GET_WITHDRAWAL_GOLD_REQUEST_HISTORY_FAILURE',

  // ----- // POST_CREATE_BANK_DEPOSITE_REQUEST // ----- //
  POST_CREATE_BANK_DEPOSITE_REQUEST_START:
    'POST_CREATE_BANK_DEPOSITE_REQUEST_START',
  POST_CREATE_BANK_DEPOSITE_REQUEST_SUCCESS:
    'POST_CREATE_BANK_DEPOSITE_REQUEST_SUCCESS',
  POST_CREATE_BANK_DEPOSITE_REQUEST_FAILURE:
    'POST_CREATE_BANK_DEPOSITE_REQUEST_FAILURE',

  // ----- // SEND_FIAT_DEPOSIT_REQUEST // ----- //
  SEND_PAY_PAL_DEPOSIT_REQUEST_START: 'SEND_PAY_PAL_DEPOSIT_REQUEST_START',
  SEND_PAY_PAL_DEPOSIT_REQUEST_SUCCESS: 'SEND_PAY_PAL_DEPOSIT_REQUEST_SUCCESS',
  SEND_PAY_PAL_DEPOSIT_REQUEST_FAILURE: 'SEND_PAY_PAL_DEPOSIT_REQUEST_FAILURE',

  // ----- // CLEAR_DEPOSIT_WINDOW_URL // ----- //
  CLEAR_DEPOSIT_WINDOW_URL: 'CLEAR_DEPOSIT_WINDOW_URL',

  // ----- // SEND_FIAT_WITHDRAWAL_REQUEST // ----- //,
  SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_START:
    'SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_START',
  SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_SUCCESS:
    'SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_SUCCESS',
  SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_FAILURE:
    'SEND_PAY_PAL_FIAT_WITHDRAWAL_REQUEST_FAILURE',

  // ----- // DELETE_WITHDRAWAL_DEPOSIT // ----- //
  DELETE_WITHDRAWAL_DEPOSIT_START: 'DELETE_WITHDRAWAL_DEPOSIT_START',
  DELETE_WITHDRAWAL_DEPOSIT_SUCCESS: 'DELETE_WITHDRAWAL_DEPOSIT_SUCCESS',
  DELETE_WITHDRAWAL_DEPOSIT_FAILURE: 'DELETE_WITHDRAWAL_DEPOSIT_FAILURE',

  // ----- // CREATE_ORDER // ----- //
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

  // ----- // CREATE_SPOT_LIMIT_ORDER // ----- //
  CREATE_STOP_LIMIT_ORDER_START: 'CREATE_STOP_LIMIT_ORDER_START',
  CREATE_STOP_LIMIT_ORDER_SUCCESS: 'CREATE_STOP_LIMIT_ORDER_SUCCESS',
  CREATE_STOP_LIMIT_ORDER_FAILURE: 'CREATE_STOP_LIMIT_ORDER_FAILURE',

  // ----- // POST_CALCULATE_MARKET_ORDER // ----- //
  POST_CALCULATE_MARKET_ORDER_START: 'POST_CALCULATE_MARKET_ORDER_START',
  POST_CALCULATE_MARKET_ORDER_SUCCESS: 'POST_CALCULATE_MARKET_ORDER_SUCCESS',
  POST_CALCULATE_MARKET_ORDER_FAILURE: 'POST_CALCULATE_MARKET_ORDER_FAILURE',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_START:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_START',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_SUCCESS:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_SUCCESS',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_FAILURE:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_FAILURE',
  CALCULATE_MARKET_ORDER_CLEAR: 'CALCULATE_MARKET_ORDER_CLEAR',

  // ----- // POST_CALCULATE_LIMIT_ORDER // ----- //
  POST_CALCULATE_LIMIT_ORDER_START: 'POST_CALCULATE_LIMIT_ORDER_START',
  POST_CALCULATE_LIMIT_ORDER_SUCCESS: 'POST_CALCULATE_LIMIT_ORDER_SUCCESS',
  POST_CALCULATE_LIMIT_ORDER_FAILURE: 'POST_CALCULATE_LIMIT_ORDER_FAILURE',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_START:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_START',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_SUCCESS:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_SUCCESS',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_FAILURE:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_FAILURE',
  CALCULATE_LIMIT_ORDER_CLEAR: 'CALCULATE_LIMIT_ORDER_CLEAR',

  // ----- // GET_AIRDROP_TRANSACTIONS // ----- //
  GET_AIRDROP_TRANSACTIONS_START: 'GET_AIRDROP_TRANSACTIONS_START',
  GET_AIRDROP_TRANSACTIONS_SUCCESS: 'GET_AIRDROP_TRANSACTIONS_SUCCESS',
  GET_AIRDROP_TRANSACTIONS_FAILURE: 'GET_AIRDROP_TRANSACTIONS_FAILURE',

  // ----- // POST_AIRDROP_TRANSFERS // ----- //
  POST_AIRDROP_TRANSFERS_START: 'POST_AIRDROP_TRANSFERS_START',
  POST_AIRDROP_TRANSFERS_SUCCESS: 'POST_AIRDROP_TRANSFERS_SUCCESS',
  POST_AIRDROP_TRANSFERS_FAILURE: 'POST_AIRDROP_TRANSFERS_FAILURE',

  // ----- // GET_REFRESH_TOKEN // ----- //
  GET_REFRESH_TOKEN_START: 'GET_REFRESH_TOKEN_START',
  GET_REFRESH_TOKEN_SUCCESS: 'GET_REFRESH_TOKEN_SUCCESS',
  GET_REFRESH_TOKEN_FAILURE: 'GET_REFRESH_TOKEN_FAILURE',

  // ----- // GET_COUNTRIES // ----- //
  GET_COUNTRIES_START: 'GET_COUNTRIES_START',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_SUCCESS',

   // ----- // GET_COUNTRIES_IDENTIFICATIONS // ----- //
  GET_COUNTRIES_IDENTIFICATION_START: 'GET_COUNTRIES_IDENTIFICATION_START',
  GET_COUNTRIES_IDENTIFICATION_SUCCESS: 'GET_COUNTRIES_IDENTIFICATION_SUCCESS',
  GET_COUNTRIES_IDENTIFICATION_FAILURE: 'GET_COUNTRIES_IDENTIFICATION_FAILURE',

    // ----- // GET_LANGUAGES_IDENTIFICATIONS // ----- //
  GET_LANGUAGES_IDENTIFICATION_START: 'GET_LANGUAGES_IDENTIFICATION_START',
  GET_LANGUAGES_IDENTIFICATION_SUCCESS: 'GET_LANGUAGES_IDENTIFICATION_SUCCESS',
  GET_LANGUAGES_IDENTIFICATION_FAILURE: 'GET_LANGUAGES_IDENTIFICATION_FAILURE',
            
    // ----- // POST_KYC_VERIFICATIONS // ----- //
  POST_KYC_VERIFICATIONS_START: 'POST_KYC_VERIFICATIONS_START',
  POST_KYC_VERIFICATIONS_SUCCESS: 'POST_KYC_VERIFICATIONS_SUCCESS',
  POST_KYC_VERIFICATIONS_FAILURE: 'POST_KYC_VERIFICATIONS_FAILURE',

  // ----- // GET_AIRPORTS // ----- //
  GET_AIRPORTS_START: 'GET_AIRPORTS_START',
  GET_AIRPORTS_SUCCESS: 'GET_AIRPORTS_SUCCESS',
  GET_AIRPORTS_FAILURE: 'GET_AIRPORTS_FAILURE',
};
